<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'ticket-template/1.0.0',
	array(
		// Identification
		//
		'label' => 'Ticket Template',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'itop-service-mgmt/3.2.0',
			'itop-portal-base/3.2.0',
			'itop-portal/3.2.0',
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'vendor/autoload.php',
			'model.ticket-template.php', // Contains the PHP code generated by the "compilation" of datamodel.ticket-template.xml
			'src/Hook/PortalUIExtension.php', // Contains the PHP code of the Portal UI extension class
		),
		'webservice' => array(
			
		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);


?>
